# ------------------------------------------------------------
#  skript-dice-roller (English edition)
#  https://github.com/Im-Tim-mI/skript-dice-roller
#  Copyright (c) 2026 廷廷小教室、廷廷的家（Tim945）
#  License: MIT + Commons Clause (see LICENSE)
# ------------------------------------------------------------

# ========================================
#  Dice Roller (1-6) - results are shown in chat to everyone in the same world
#  Available to all players
# ========================================

command /dice1:
    trigger:
        set {_d1} to a random integer between 1 and 6

        loop all players in player's world:
            send "&e%player's name% &f1st die: &a%{_d1}%" to loop-player


command /dice2:
    trigger:
        set {_d1} to a random integer between 1 and 6
        set {_d2} to a random integer between 1 and 6
        set {_sum} to {_d1} + {_d2}

        loop all players in player's world:
            send "&e%player's name% &f1st die: &a%{_d1}% &f2nd die: &a%{_d2}% &fTotal: &6%{_sum}%" to loop-player


command /dice3:
    trigger:
        set {_d1} to a random integer between 1 and 6
        set {_d2} to a random integer between 1 and 6
        set {_d3} to a random integer between 1 and 6
        set {_sum} to {_d1} + {_d2} + {_d3}

        loop all players in player's world:
            send "&e%player's name% &f1st die: &a%{_d1}% &f2nd die: &a%{_d2}% &f3rd die: &a%{_d3}% &fTotal: &6%{_sum}%" to loop-player
